// <auto-generated />
using GincanaPassagensBiblicas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GincanaPassagensBiblicas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260217013932_AddPassagem")]
    partial class AddPassagem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("GincanaPassagensBiblicas.Models.Frase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contexto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Passagem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Frases");
                });

            modelBuilder.Entity("GincanaPassagensBiblicas.Models.Pontuacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FraseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FraseId")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pontuacoes");
                });

            modelBuilder.Entity("GincanaPassagensBiblicas.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GincanaPassagensBiblicas.Models.Frase", b =>
                {
                    b.HasOne("GincanaPassagensBiblicas.Models.Usuario", "Usuario")
                        .WithMany("Frases")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GincanaPassagensBiblicas.Models.Pontuacao", b =>
                {
                    b.HasOne("GincanaPassagensBiblicas.Models.Frase", "Frase")
                        .WithOne("Pontuacao")
                        .HasForeignKey("GincanaPassagensBiblicas.Models.Pontuacao", "FraseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GincanaPassagensBiblicas.Models.Usuario", "Usuario")
                        .WithMany("Pontuacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frase");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GincanaPassagensBiblicas.Models.Frase", b =>
                {
                    b.Navigation("Pontuacao");
                });

            modelBuilder.Entity("GincanaPassagensBiblicas.Models.Usuario", b =>
                {
                    b.Navigation("Frases");

                    b.Navigation("Pontuacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
